// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: gRPC/greet.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace WPF.NETCore {
  /// <summary>
  /// The greeting service definition.
  /// </summary>
  public static partial class Greeter
  {
    static readonly string __ServiceName = "greet.Greeter";

    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    static readonly grpc::Marshaller<global::WPF.NETCore.HelloRequest> __Marshaller_greet_HelloRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::WPF.NETCore.HelloRequest.Parser));
    static readonly grpc::Marshaller<global::WPF.NETCore.HelloReply> __Marshaller_greet_HelloReply = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::WPF.NETCore.HelloReply.Parser));
    static readonly grpc::Marshaller<global::Google.Protobuf.WellKnownTypes.Empty> __Marshaller_google_protobuf_Empty = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Google.Protobuf.WellKnownTypes.Empty.Parser));
    static readonly grpc::Marshaller<global::WPF.NETCore.MessageAppFileList> __Marshaller_greet_MessageAppFileList = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::WPF.NETCore.MessageAppFileList.Parser));
    static readonly grpc::Marshaller<global::WPF.NETCore.MessageTextRequest> __Marshaller_greet_MessageTextRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::WPF.NETCore.MessageTextRequest.Parser));
    static readonly grpc::Marshaller<global::WPF.NETCore.MessageTextList> __Marshaller_greet_MessageTextList = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::WPF.NETCore.MessageTextList.Parser));
    static readonly grpc::Marshaller<global::WPF.NETCore.MessageSubscribe> __Marshaller_greet_MessageSubscribe = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::WPF.NETCore.MessageSubscribe.Parser));
    static readonly grpc::Marshaller<global::WPF.NETCore.MessageSubscribeResponse> __Marshaller_greet_MessageSubscribeResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::WPF.NETCore.MessageSubscribeResponse.Parser));

    static readonly grpc::Method<global::WPF.NETCore.HelloRequest, global::WPF.NETCore.HelloReply> __Method_SayHello = new grpc::Method<global::WPF.NETCore.HelloRequest, global::WPF.NETCore.HelloReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SayHello",
        __Marshaller_greet_HelloRequest,
        __Marshaller_greet_HelloReply);

    static readonly grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::WPF.NETCore.MessageAppFileList> __Method_GetAppFileList = new grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::WPF.NETCore.MessageAppFileList>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetAppFileList",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_greet_MessageAppFileList);

    static readonly grpc::Method<global::WPF.NETCore.MessageTextRequest, global::WPF.NETCore.MessageTextList> __Method_GetMessageList = new grpc::Method<global::WPF.NETCore.MessageTextRequest, global::WPF.NETCore.MessageTextList>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetMessageList",
        __Marshaller_greet_MessageTextRequest,
        __Marshaller_greet_MessageTextList);

    static readonly grpc::Method<global::WPF.NETCore.MessageSubscribe, global::WPF.NETCore.MessageSubscribeResponse> __Method_Subscribe = new grpc::Method<global::WPF.NETCore.MessageSubscribe, global::WPF.NETCore.MessageSubscribeResponse>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "Subscribe",
        __Marshaller_greet_MessageSubscribe,
        __Marshaller_greet_MessageSubscribeResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::WPF.NETCore.GreetReflection.Descriptor.Services[0]; }
    }

    /// <summary>Client for Greeter</summary>
    public partial class GreeterClient : grpc::ClientBase<GreeterClient>
    {
      /// <summary>Creates a new client for Greeter</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public GreeterClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for Greeter that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public GreeterClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected GreeterClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected GreeterClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      /// Sends a greeting
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::WPF.NETCore.HelloReply SayHello(global::WPF.NETCore.HelloRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SayHello(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Sends a greeting
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::WPF.NETCore.HelloReply SayHello(global::WPF.NETCore.HelloRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SayHello, null, options, request);
      }
      /// <summary>
      /// Sends a greeting
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::WPF.NETCore.HelloReply> SayHelloAsync(global::WPF.NETCore.HelloRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SayHelloAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Sends a greeting
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::WPF.NETCore.HelloReply> SayHelloAsync(global::WPF.NETCore.HelloRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SayHello, null, options, request);
      }
      public virtual global::WPF.NETCore.MessageAppFileList GetAppFileList(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetAppFileList(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::WPF.NETCore.MessageAppFileList GetAppFileList(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetAppFileList, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::WPF.NETCore.MessageAppFileList> GetAppFileListAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetAppFileListAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::WPF.NETCore.MessageAppFileList> GetAppFileListAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetAppFileList, null, options, request);
      }
      public virtual global::WPF.NETCore.MessageTextList GetMessageList(global::WPF.NETCore.MessageTextRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetMessageList(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::WPF.NETCore.MessageTextList GetMessageList(global::WPF.NETCore.MessageTextRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetMessageList, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::WPF.NETCore.MessageTextList> GetMessageListAsync(global::WPF.NETCore.MessageTextRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetMessageListAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::WPF.NETCore.MessageTextList> GetMessageListAsync(global::WPF.NETCore.MessageTextRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetMessageList, null, options, request);
      }
      public virtual grpc::AsyncServerStreamingCall<global::WPF.NETCore.MessageSubscribeResponse> Subscribe(global::WPF.NETCore.MessageSubscribe request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Subscribe(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncServerStreamingCall<global::WPF.NETCore.MessageSubscribeResponse> Subscribe(global::WPF.NETCore.MessageSubscribe request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_Subscribe, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override GreeterClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new GreeterClient(configuration);
      }
    }

  }
}
#endregion
